from loading_dataset import *
from score_model import *

"""# Test a logistic regression model
score_logistic_torch("../models/TestLogiReg.sav", reduced_dataset_standard15)

# Test SVM with linear kernel
score_SVM_sklearn("../models/TestSVM.sav", reduced_dataset_standard15)"""


"""print("\n\n--------------------- Logi Reg -----------------")
accuracy, recall, f1score, _, _ = training_accuracy_logistic("../models/LogiRegReduced15.sav", reduced_dataset_standard15)
print("15 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_logistic("../models/LogiRegReduced30.sav", reduced_dataset_standard30)
print("30 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_logistic("../models/LogiRegFullStd.sav", Full_dataset_standard)
print("Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_logistic("../models/LogiRegFull.sav", Full_dataset)
print("Non-Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_logistic("../models/LogiRegPCA90.sav", pca_dataset90)
print("PCA 90%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_logistic("../models/LogiRegPCA95.sav", pca_dataset95)
print("PCA 95%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])

print("\n\n--------------------- SVM LINEAR -----------------")
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/LinearReduced15.sav", reduced_dataset_standard15)
print("15 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/LinearReduced30.sav", reduced_dataset_standard30)
print("30 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/LinearFullStd.sav", Full_dataset_standard)
print("Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
#accuracy, recall, f1score = score_SVM("../models/LogiRegFull.sav", Full_dataset)
#print("Non-Standardized  |", accuracy, " | ", recall, " | ", f1score)
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/LinearPCA90.sav", pca_dataset90)
print("PCA 90%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/LinearPCA95.sav", pca_dataset95)
print("PCA 95%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])


print("\n\n--------------------- SVM RBF -----------------")
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/RbfReduced15.sav", reduced_dataset_standard15)
print("15 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/RbfReduced30.sav", reduced_dataset_standard30)
print("30 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/RbfFullStd.sav", Full_dataset_standard)
print("Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/RbfFull.sav", Full_dataset)
print("Non-Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/RbfPCA90.sav", pca_dataset90)
print("PCA 90%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/RbfPCA95.sav", pca_dataset95)
print("PCA 95%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])


print("\n\n--------------------- SVM SIGMOID -----------------")
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/SigmoidReduced15.sav", reduced_dataset_standard15)
print("15 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/SigmoidReduced30.sav", reduced_dataset_standard30)
print("30 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/SigmoidFullStd.sav", Full_dataset_standard)
print("Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/SigmoidFull.sav", Full_dataset)
print("Non-Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/SigmoidPCA90.sav", pca_dataset90)
print("PCA 90%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/SigmoidPCA95.sav", pca_dataset95)
print("PCA 95%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])


print("\n\n--------------------- SVM Poly1 -----------------")
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly1Reduced15.sav", reduced_dataset_standard15)
print("15 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly1Reduced30.sav", reduced_dataset_standard30)
print("30 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly1FullStd.sav", Full_dataset_standard)
print("Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
#_, accuracy, recall, f1score = score_SVM("../models/Poly1Full.sav", Full_dataset)
#print("Non-Standardized  |", accuracy, " | ", recall, " | ", f1score)
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly1PCA90.sav", pca_dataset90)
print("PCA 90%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly1PCA95.sav", pca_dataset95)
print("PCA 95%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])


print("\n\n--------------------- SVM Poly2 -----------------")
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly2Reduced15.sav", reduced_dataset_standard15)
print("15 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly2Reduced30.sav", reduced_dataset_standard30)
print("30 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly2FullStd.sav", Full_dataset_standard)
print("Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
#_, accuracy, recall, f1score = score_SVM("../models/Poly2Full.sav", Full_dataset)
#print("Non-Standardized  |", accuracy, " | ", recall, " | ", f1score)
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly2PCA90.sav", pca_dataset90)
print("PCA 90%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly2PCA95.sav", pca_dataset95)
print("PCA 95%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])


print("\n\n--------------------- SVM Poly3 -----------------")
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly3Reduced15.sav", reduced_dataset_standard15)
print("15 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly3Reduced30.sav", reduced_dataset_standard30)
print("30 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly3FullStd.sav", Full_dataset_standard)
print("Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
#_, accuracy, recall, f1score = score_SVM("../models/Poly2Full.sav", Full_dataset)
#print("Non-Standardized  |", accuracy, " | ", recall, " | ", f1score)
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly3PCA90.sav", pca_dataset90)
print("PCA 90%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly3PCA95.sav", pca_dataset95)
print("PCA 95%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])


print("\n\n--------------------- SVM Poly4 -----------------")
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly4Reduced15.sav", reduced_dataset_standard15)
print("15 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly4Reduced30.sav", reduced_dataset_standard30)
print("30 features  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly4FullStd.sav", Full_dataset_standard)
print("Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly4Full.sav", Full_dataset)
print("Non-Standardized  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly4PCA90.sav", pca_dataset90)
print("PCA 90%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
accuracy, recall, f1score, _, _ = training_accuracy_SVM("../models/Poly4PCA95.sav", pca_dataset95)
print("PCA 95%  |", str(accuracy*100)[:9], " | ", str(recall*100)[:9], " | ", str(f1score*100)[:9])
"""